### ISSUE TITLE
Use async execute instead of async run

### ISSUE THREAD

**Issue by Shiva953** [NoNameLmao/emberbot#14]
Though both are used for handling command interactions, the current version of discordJS prefers the use of async execute over async run

**Comment by NoNameLmao** [comment]
alright then, sure

**Comment by NoNameLmao** [comment]
done in commit [4ea19ec](https://github.com/NoNameLmao/emberbot/commit/4ea19ecd206456a55a8340d587a899ceca3cde3a)
